dist: xenial
language: php
php:
  - 7.4.0
  - 7.4
cache:
  directories:
    - ./vendor/
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-source
  - composer update --dry-run roave/security-advisories
script:
  - composer run tests
  - ./vendor/bin/php-coveralls
matrix:
  fast_finish: true
